[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc_version = "0.8.20"
sort_imports = true
evm_version = "shanghai"

[fmt]
line_length = 120
tab_width = 4
wrap_comments = true
sort_imports = true
